import pathlib
lines = []
a = lines.append
a("# FlowTwin — Collective Traffic Routing")
a("")
a("**FlowTwin** is a geographic, interactive implementation and *extension* of the")
a("[collective-routing concept](https://devpost.com/software/gigglemaps-ebnzh0).")
a("")
a("Normal navigation: *What is the fastest route for one traveller?*")
a("")
a("FlowTwin: **What allocation minimizes network-wide travel time?**")
a("")
a("Given origin, destination, and number of travellers:")
a("")
a("1. **geocodes** locations (Nominatim - free, no API key)")
a("2. **obtains the real road network** from OpenStreetMap via OSMnx")
a("3. **converts to a directed graph** with real lengths, estimated speeds/capacities")
a("4. **snaps** origin/destination to nearest graph nodes")
a("5. finds the **baseline** shortest route (Dijkstra, own implementation)")
a("6. **generates candidate routes** (Yen k-shortest + penalty corridors)")
a("7. **simulates congestion** with nonlinear BPR flow model")
a("8. **distributes travellers** with damped MSA-style flow assignment")
a("9. **compares** collective vs baseline with execution-derived metrics")
a("")
a("> Data integrity: numbers from actual execution. Capacities/speeds estimated. Demand simulated.")
a("")
a("---")
a("")
a("## Architecture")
a("")
a("```")
a("OpenStreetMap -> OSMnx -> NetworkX MultiDiGraph -> Snap OD -> Baseline + Proposed -> Evaluation")
a("```")
a("")
a("## Algorithm layer")
a("")
a("Decoupled from HTTP/UI: baseline.py, candidates.py, proposed.py, evaluation.py")
a("")
a("## Installation")
a("")
a("```bash")
a("python3 -m venv backend/.venv")
a("backend/.venv/bin/pip install -r backend/requirements.txt")
a("```")
a("")
a("## Running")
a("")
a("```bash")
a("# backend:  cd backend && .venv/bin/python -m uvicorn main:app --port 8000")
a("# frontend: open frontend/index.html")
a("# experiments: cd backend && .venv/bin/python experiments/run_experiment.py")
a("```")
a("")
a("Endpoints: /health, /api/geocode, /api/run, /api/results/{id}")
a("")
a("## Complexity")
a("")
a("| Component | Time | Space |")
a("|-----------|------|-------|")
a("| Dijkstra | O(E log V) | O(V) |")
a("| Yen k-shortest | O(k*V*(E log V)) | O(k*V) |")
a("| Optimizer/iter | O(k*(E log V)) | O(E) |")
a("")
a("## Testing")
a("")
a("```bash")
a("cd backend && .venv/bin/python -m pytest tests/ -v")
a("```")
a("")
a("## Limitations")
a("")
a("- Capacities/speeds estimated (flagged *_estimated)")
a("- Demand is simulated, not live traffic")
a("- Alternatives within 1.3x free-flow threshold")
a("- BPR params are literature defaults")
a("")
a("## Attribution")
a("")
a("Map: OSM (ODbL). Geocoding: Nominatim. Built with FastAPI, OSMnx, NetworkX, Leaflet.")
a("")
a("Independent implementation inspired by GiggleMaps.")
pathlib.Path("README.md").write_text("\n".join(lines)+"\n")
print("ok", len(lines))
